import React from 'react';
import { motion } from 'framer-motion';
import { ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';

const PrivacyPolicy = () => {
    return (
        <div className="min-h-screen bg-bg-deep text-white font-sans selection:bg-primary/30">
            <nav className="fixed top-0 left-0 right-0 h-24 flex items-center px-8 sm:px-20 z-50 backdrop-blur-md border-b border-white/5">
                <Link to="/" className="flex items-center gap-2 text-text-secondary hover:text-white transition-colors group text-sm uppercase tracking-widest font-medium">
                    <ArrowLeft size={18} className="transition-transform group-hover:-translate-x-1" />
                    Back to Home
                </Link>
            </nav>

            <main className="max-w-4xl mx-auto px-8 sm:px-20 pt-40 pb-20">
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6 }}
                >
                    <h1 className="text-4xl sm:text-5xl font-medium mb-4 tracking-tight">Privacy Policy</h1>
                    <p className="text-text-secondary mb-12 font-normal">Last updated: January 28, 2026</p>

                    <div className="prose prose-invert prose-p:text-text-secondary prose-p:leading-relaxed prose-headings:text-white prose-headings:font-medium prose-headings:tracking-tight space-y-12">
                        <section>
                            <p>
                                This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                            </p>
                            <p>
                                We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl mb-4">Interpretation and Definitions</h2>
                            <h3 className="text-xl mb-2">Interpretation</h3>
                            <p>
                                The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                            </p>
                            <h3 className="text-xl mb-2 mt-6">Definitions</h3>
                            <p>For the purposes of this Privacy Policy:</p>
                            <ul className="list-disc pl-5 mt-4 space-y-2 text-text-secondary">
                                <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                                <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                                <li><strong>Application</strong> refers to Codino, the software program provided by the Company.</li>
                                <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to Codino.</li>
                                <li><strong>Country</strong> refers to: Bangladesh</li>
                                <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
                                <li><strong>Personal Data</strong> (or "Personal Information") is any information that relates to an identified or identifiable individual.</li>
                                <li><strong>Service</strong> refers to the Application.</li>
                                <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-2xl mb-4">Collecting and Using Your Personal Data</h2>
                            <h3 className="text-xl mb-2">Types of Data Collected</h3>
                            <h4 className="text-lg font-medium mt-4">Personal Data</h4>
                            <p>
                                While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to: Email address, First name and last name.
                            </p>
                            <h4 className="text-lg font-medium mt-6">Usage Data</h4>
                            <p>
                                Usage Data is collected automatically when using the Service. It may include information such as Your Device's IP address, browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, unique device identifiers and other diagnostic data.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl mb-4">Use of Your Personal Data</h2>
                            <p>The Company may use Personal Data for the following purposes:</p>
                            <ul className="list-disc pl-5 mt-4 space-y-2 text-text-secondary">
                                <li>To provide and maintain our Service, including to monitor usage.</li>
                                <li>To manage Your Account and registration as a user.</li>
                                <li>For the performance of a contract.</li>
                                <li>To contact You regarding updates or informative communications.</li>
                                <li>To provide You with news, special offers and general information.</li>
                                <li>To manage Your requests.</li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-2xl mb-4">Retention of Your Personal Data</h2>
                            <p>
                                The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. Account information is typically retained for the duration of your account relationship plus up to 24 months. Support tickets and usage statistics are also retained for up to 24 months.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl mb-4">Delete Your Personal Data</h2>
                            <p>
                                You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. You may update, amend, or delete Your information at any time by signing in to Your Account or by contacting us.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl mb-4">Security of Your Personal Data</h2>
                            <p>
                                The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl mb-4">Contact Us</h2>
                            <p>If you have any questions about this Privacy Policy, You can contact us:</p>
                            <p className="mt-2">By email: <span className="text-primary font-medium">madmaxsecondac@gmail.com</span></p>
                        </section>
                    </div>
                </motion.div>
            </main>

            <footer className="max-w-7xl mx-auto px-8 sm:px-20 py-12 border-t border-white/5 flex justify-center text-[0.7rem] font-medium text-text-muted uppercase tracking-[0.2em]">
                <span>&copy; 2026 CODINO.</span>
            </footer>
        </div>
    );
};

export default PrivacyPolicy;
